### ISSUE TITLE
No "About Chewing Editor" Window

### ISSUE THREAD

**Issue by ss1h2a3tw** [chewing/chewing-editor#104]
Platform: Archlinux
Using libchewing and qt5-base and qt5-tools from official repo.
Neither building from git nor AUR (chewing-editor-git) works for me.
But "About Qt" works.

**Comment by iblis17** [comment]
Hi @ss1h2a3tw ! 
This is a work in progress.
Please consider #25 .

**Comment by ss1h2a3tw** [comment]
Oh, I didn't notice that XD.
