### ISSUE TITLE
add three-wchar word, returns 0 but the three-wchar word is not added

### ISSUE THREAD

**Issue by YWJamesLin** [chewing/chewing-editor#106]
When I run add feature, and add 
```
爽炸天（ㄕㄨㄤˇ ㄓㄚˋ ㄊ一ㄢ ）
```
the program returns 0 but the phrase is not added.
![screenshot_20160321_131030](https://cloud.githubusercontent.com/assets/4758887/13911118/26e28916-ef67-11e5-8e21-f3c6b05cefc6.png)

![screenshot_20160321_131303](https://cloud.githubusercontent.com/assets/4758887/13911116/26e10974-ef67-11e5-8eb8-db2957cd2e9b.png)

![screenshot_20160321_131337](https://cloud.githubusercontent.com/assets/4758887/13911117/26e162a2-ef67-11e5-963e-71c6b6e48d32.png)

**Comment by david50407** [comment]
When `chewing_userphrase_add` returns `NULL` (`0`), it usually means add failed.

**Comment by YWJamesLin** [comment]
Ok, I understand. But this phrase should not failed to be added.
By the way, the phrase I put on to be an example of the issue is wrong. 
"bopomofo" should be "ㄕㄨㄤˇ ㄓㄚˋ ㄊ一ㄢ "
but this failed, too.

**Comment by david50407** [comment]
Try using `ㄧ`(bopomofo) instead of `一`(Chinese word)

**Comment by YWJamesLin** [comment]
By doing replacement, this fixed my issue, 2 example are tested.

**Comment by david50407** [comment]
Maybe we have to auto-convert `一`(phone) to `ㄧ`(Bopomofo) or give a warning while users type non-bopomofo words or any other poka-yoke solutions.

**Comment by robert501128** [comment]
Hi, I adopt the recommendation of @david50407 and add a function to automatically change 一(phone) to ㄧ(Bopomofo) , please check it out!
[https://github.com/robert501128/chewing-editor/blob/master/src/model/UserphraseModel.cpp](url)
