### ISSUE TITLE
Add Hotkeys to do something

### ISSUE THREAD

**Issue by YWJamesLin** [chewing/chewing-editor#107]
I'd like to add some key binding to the application.
example. ctrl + w to close the app. ctrl + a to add phrase, etc.
Maybe I should put on a issue like this to obtain some opinions XD

**Comment by Chocobo1** [comment]
>ctrl + w to close the app

there is already alt + f4, and it works universally on all OS.

> ctrl + a: add phrase

agree with this one.

some ideas, how about:
ctrl + d: delete entry
ctrl + r: refresh list

**Comment by cyng93** [comment]
I suppose "delete" would be a better choice than "ctrl+d" ?

**Comment by YWJamesLin** [comment]
Great!
```
Delete : delete entry
ctrl + r : refresh list
enter: modify existing phrase
```

`there is already alt + f4 and it works universally on all OS.`
Since I use Linux with Awesome WM, it does not have this kind of hotkey.
That is why some Linux application has hotkey Ctrl + Q to close the application.

**Comment by david50407** [comment]
>> ctrl + w to close the app

> there is already alt + f4 and it works universally on all OS.

Alt+F4 also not closing application on Mac OS X. :'(

> However, some Linux applications have hotkey Ctrl + Q to close the application, and I can directly close the application.

On Mac OS X, Cmd+Q usually closes the application, and on Windows, Ctrl+Q/W often set as closing application, too.

(attachment is the menu in Firefox on OS X, it uses Cmd+Q to close app.)
![2016-03-25 10 16 18](https://cloud.githubusercontent.com/assets/841969/14036309/a7846202-f272-11e5-936a-b016a2d8ac56.png)

**Comment by david50407** [comment]
I found that on OS X, it will auto-add the `close` item on main menu

![2016-03-25 10 53 30](https://cloud.githubusercontent.com/assets/841969/14036819/e62480aa-f277-11e5-97c9-feeb544e2d74.png)

**Comment by Chocobo1** [comment]
>Since I use Linux with Awesome WM, it does not have this kind of hotkey.
...
>Alt+F4 also not closing application on Mac OS X.

Thanks for the info since I don't have a mac & can't test all DEs out there.

> However, some Linux applications have hotkey Ctrl + Q to close the application, and I can directly close the application.

I can agree with `Ctrl + Q` for exit action.

**Comment by Chocobo1** [comment]
Please test #138.

It may bind to different keys than what we agreed on, because Qt has defined some "StandardKeys": https://doc.qt.io/qt-5/qkeysequence.html#StandardKey-enum

should be better if we follow that.
