### ISSUE TITLE
Unable to input words with ibus-chewing on FreeBSD 10.2

### ISSUE THREAD

**Issue by mangokingTW** [chewing/chewing-editor#114]
There is a weird bug that I cannot use ibus-chewing to input words on any place of chewing-editor.
![](http://i.imgur.com/w2C1854.png)
However ibus-chewing works normally on other applications.
By the way, chewing-editor is functioning properly.

The environment:
OS : FreeBSD 10.2-release-p14 arm64
DE: KDE

**Comment by david50407** [comment]
Try `ibus-qt`?

**Comment by mangokingTW** [comment]
Doesn't work :/

**Comment by mangokingTW** [comment]
I do some mistakes at settings.
In .xinitrc :
> export QT_IM_MODULE=xim
should be replaced to
> export QT_IM_MODULE=ibus

Sorry for my foolish.
