### ISSUE TITLE
display inconsistent

### ISSUE THREAD

**Issue by zmcx16** [chewing/chewing-editor#117]
After I added "趴(ㄆㄚ)", this program display:
![2016-03-23-163428_1366x768_scrot](https://cloud.githubusercontent.com/assets/7957361/13980010/f876cd1a-f116-11e5-8f27-508cdfd56ddc.png)

then I closed "chewing-editor" and re-executed it, chewing-editor showed:
![2016-03-23-163444_1366x768_scrot](https://cloud.githubusercontent.com/assets/7957361/13980083/733b71e0-f117-11e5-9d0c-f85ce7a4f58b.png)

Is it normal? or I think it is conflicting.

**Comment by zmcx16** [comment]
I found it's same as Ref: #100, sorry.

**Comment by david50407** [comment]
Duplicated to https://github.com/chewing/chewing-editor/issues/91

**Comment by Chocobo1** [comment]
also dup of #115.
