### ISSUE TITLE
[SOLVED]cannot view Mandarin Phonetic Symbols on Linux Mint 17.3 "Rosa" on VirtualBox 5.0.16

### ISSUE THREAD

**Issue by FuGu0416** [chewing/chewing-editor#119]
When I type in some word, all the Mandarin Phonetic Symbols showed in the chewing-editor are appeared as 口口口
![fossapc hackpad com_m8geukgkacm_p](https://cloud.githubusercontent.com/assets/17677281/13983631/d4656a3e-f12b-11e5-832d-f006567cd8eb.png)
However, the  Mandarin Phonetic Symbols can be seen normal in other text-editor software(see example below that has 'ㄇ' and 'ㄓ').
![11](https://cloud.githubusercontent.com/assets/17677281/13983630/d14b6362-f12b-11e5-82c2-ef33ed15befe.JPG)

**Comment by david50407** [comment]
What version of Qt you have?
If is `< 5.3.0`, try `QT_HARFBUZZ=old ./chewing-editor`

**Comment by FuGu0416** [comment]
OK, I find out that my version of Qt is quite old.
Thanks, it works now.
