### ISSUE TITLE
Identify word "一" and bopomofo "ㄧ"

### ISSUE THREAD

**Issue by wcchang1115** [chewing/chewing-editor#123]
When adding new phrase, it's hard to identify word "一" and bopomofo "ㄧ" in bopomofo field.
In this way, it cannot be noticed until clicking the "OK" button and reaching the warning massage.

Is this a same kind issue as #108 ?

**Comment by david50407** [comment]
yes, it's duplicated .

**Comment by wcchang1115** [comment]
OK, THX!
Should I close this issue?
