### ISSUE TITLE
bopomofo symbols display problems with different input method used in terminal 

### ISSUE THREAD

**Issue by redfish-lee** [chewing/chewing-editor#125]
I've encounter a problem that when **Chewing user phrase editor** works fine at this exeucutution, maybe the **bopomofo symbols** couldn't display well at next execution. And there's no settings changed between these two executions.
![first execution](https://cloud.githubusercontent.com/assets/16261646/14029500/76455b4a-f23d-11e5-91f3-80b35584559f.PNG)

![second execution](https://cloud.githubusercontent.com/assets/16261646/14029509/7a5c0210-f23d-11e5-8703-b7b4b6474bd0.PNG)

I'm not sure the problem is caused by input methods.
Because I've test to use the same input methods for consecutive executions for more than 10 times and the problem just happened in random.

My environment
- Ubuntu 14.04
- iBus chewing

I think build and make works fine, but anyway these are what I've used to build through:
- `libchewing3` 0.4.0-3
- `cmake` 3.2
- `qt5-default`, `qttools5-dev-tools` and `libqt5webkit5-dev` 
- `gcc` 4.8.4

any comments is appreciated (:

**Comment by david50407** [comment]
What is your Qt version? (`Help -> About Qt` in chewing editor.)

**Comment by BarneyCw** [comment]
I also use Ubuntu 14.04 and I've encounter the same problem as yours.
I solved by : " QT_HARFBUZZ=old ./chewing-editor "

Ref: https://github.com/chewing/chewing-editor/issues/71

**Comment by redfish-lee** [comment]
`$ QT_HARFBUZZ=old ./chewing-editor` works! 

via 
> https://bugs.archlinux.org/task/38355
> http://doc.qt.io/qt-5/configure-options.html

Qt5 includes both the old harfbuzz (harfbuzz.old) and the new harfbuzz.
Configure with `-qt-harfbuzz` or `-system-harfbuzz` options.

However, `-no-harfbuzz` can be set at runtime by setting `QT_HARFBUZZ` environment variable to **old**
and that's the solution @BarneyCw suggested.

Thanks a lot!
