### ISSUE TITLE
Hide Close from File menu on OS X

### ISSUE THREAD

**Issue by david50407** [chewing/chewing-editor#129]
As screenshot below, on OS X, there will be a built-in `Quit` item in the main menu.
For matching OS X users' habit and avoiding ambiguous , maybe we can hide `Close` from `File` menu?

![2016-03-25 10 53 30](https://cloud.githubusercontent.com/assets/841969/14036823/05590e14-f278-11e5-83a9-4521d645d891.png)

**Comment by david50407** [comment]
http://doc.qt.io/qt-5/osx-issues.html#menu-bar
And say as the document in Qt, should we move `About Chewing Editor` into the main menu?

**Comment by Chocobo1** [comment]
>For matching OS X users' habit and avoiding ambiguous , maybe we can hide Close from File menu?

can you elaborate more? don't have a mac to see what you're saying.

**Comment by david50407** [comment]
On OS X, there will be at least one main menu called Application Menu, it ofter contains highly related actions to the application, like `about`, `preference/setting`, `quit`. 

![2016-03-25 12 55 16](https://cloud.githubusercontent.com/assets/841969/14038238/d7884a2a-f288-11e5-9985-dbacef3069c2.png)

And the `File` menu is like other platforms but moved out these items showed in Application menu.

![2016-03-25 12 57 23](https://cloud.githubusercontent.com/assets/841969/14038256/223149f0-f289-11e5-974b-6acda3273d12.png)

It also moves `about` from `Help` to Application menu.

![2016-03-25 12 58 42](https://cloud.githubusercontent.com/assets/841969/14038266/51fa71f2-f289-11e5-81b7-62927694921b.png)

**Comment by Chocobo1** [comment]
I understand now (but a bit vaguely...), seems easy to fix.
Patches welcome, if the patch doesn't clog up the code readability.
