### ISSUE TITLE
cannot type chewing when I switch the window ( Ubuntu14.04)

### ISSUE THREAD

**Issue by robert501128** [chewing/chewing-editor#134]
When I am using the chewing-editor, everything goes well
![screenshot from 2016-03-25 15 15 03](https://cloud.githubusercontent.com/assets/12629785/14039879/6fffe05c-f29c-11e5-8bbb-1a896c4a0594.png)

However, when I switch the window to other processes, such as chrome, and type some words by chewing, and then go back to the chewing-editor, I can only type English.

I switch my window and type chewing in chrome
![image](https://cloud.githubusercontent.com/assets/12629785/14039922/cd9591b2-f29c-11e5-91e3-b4e722362430.png)
And then I return to chewing-editor, but I can only type English
![image](https://cloud.githubusercontent.com/assets/12629785/14039929/e462dfe4-f29c-11e5-8701-dc7a07e1b0f2.png)
I have to switch my input method to English and go back to chewing by typing "cmd+space" twice, and then I can type chewing again

**Comment by momocow** [comment]
This problem isn't appear in my environment.
Maybe it's related to your system setting, e.g. **the default input method**.
Check about it if you let English input be the default one.

**Comment by robert501128** [comment]
I have tried. I deleted all of input methods except chewing, but the problem still appear.

**Comment by kidwm** [comment]
That should be a problem about Qt integration or ibus-chewing and out of scope of this project.
