### ISSUE TITLE
Word selecting problem while typing

### ISSUE THREAD

**Issue by star12thstar** [chewing/chewing-editor#139]
While typing with 新酷音,you can only select the word you want by using number buttons, not digit keyboard.
i.e. you want to type"選字", but it comes up with"選自". when you want select the correct one for the second word, you can only use 1,2,and so on, you can't use ↓　↑ to do this action.
---------------------------------------------
Well,actually i can't make sure have this issue been reported or not, cuz i think it's the first problem we are faced with while using 新酷音.(But I can't find reported issues related to the one i found, if it has been reported, please let me know, thx)

**Comment by david50407** [comment]
This is not related to chewing-editor.
Please report to the project you used for chewing, like: ibus-chewing, fctix-chewing, etc.

**Comment by star12thstar** [comment]
ok,get it! thank you!
