### ISSUE TITLE
Add filter to the search bar of chewing-editor

### ISSUE THREAD

**Issue by momocow** [chewing/chewing-editor#140]
I think the implement of filter on the search bar can benefit when editing phrases.
![image](https://cloud.githubusercontent.com/assets/17778751/14040950/64f5a9f2-f2a7-11e5-89e9-dbf2b01fdaa6.png)

For example, you want to find a phrase with the filter, "(('交通' or '交大') and '網路')" , then the result shows '交通大學網路工程所', '交大招生入學網路報名系統' and so on.

**Comment by david50407** [comment]
but why? are we use the editor for searching phrase we liked?
or we just want to find the phrase incorrectly and fix it right? (or just find out if the phrase is in the list)

**Comment by kidwm** [comment]
I think the current simple filter is good enough.
