### ISSUE TITLE
Add a dialog when adding/modifying a wrong phrase/bopomofo

### ISSUE THREAD

**Issue by hwhung0111** [chewing/chewing-editor#141]
When I'm modify a phrase, I type a wrong phrase and click OK button. It will disappear directly and remove the phrase from chewing-editor without a warning. I think it need a dialog to tell me I type a wrong phrase, and let me choose if I want to correct the phrase or restore the phrase instead of removing the phrase.

**Comment by david50407** [comment]
duplicated to https://github.com/chewing/chewing-editor/issues/109
