### ISSUE TITLE
When I was typing I can't see any Zhuyin

### ISSUE THREAD

**Issue by terrynini** [chewing/chewing-editor#142]
I run chewing on gcin

**Comment by david50407** [comment]
any screenshots?

**Comment by terryfox38514** [comment]
it can't be perform by screenshots ,I guess
If I want to type 你 , I have to type ㄋ一ˇ 
But I can’t see any Cuyin  during  the process of typing 
I can only see 你 after I type ˇ

**Comment by terryfox38514** [comment]
Addition to this 
chewing-editor can not remeber the Chuyin of the word 
they all become the symbol of  sqare

**Comment by terryfox38514** [comment]
but 詞音 still work well at the same time

**Comment by david50407** [comment]
Is your problem as same as https://github.com/chewing/chewing-editor/issues/125?

**Comment by terryfox38514** [comment]
that can fix the problem about displaying Chuyin in editor but I can't type any chinese word or Chuyin in "add" still

**Comment by jserv** [comment]
We usually say Zhuyin or Bopomofo: https://en.wikipedia.org/wiki/Bopomofo

**Comment by kidwm** [comment]
try to use ibus-chewing?

**Comment by jserv** [comment]
No further action.
