### ISSUE TITLE
Able to copy userphrase and paste it outside of the chewing-editor

### ISSUE THREAD

**Issue by FuGu0416** [chewing/chewing-editor#151]
I was able to copy(with Ctrl+C) an userphrase and paste(with Ctrl+V) it onto other text-editor. Is it an intentional feature or a bug?
![99](https://cloud.githubusercontent.com/assets/17677281/14058508/6926d4fe-f35d-11e5-8cc5-60d8f7c0beba.JPG)

**Comment by kidwm** [comment]
why not to do this way?
