### ISSUE TITLE
Square Boxes for BoPoMoFo 

### ISSUE THREAD

**Issue by eugenelet** [chewing/chewing-editor#152]
I can't really track this bug down.
Sometime when I open chewing_editor, square boxes will appear for the BoPoMoFo part. When I re-open, it's work as usual.

With Boxes:
![image](https://cloud.githubusercontent.com/assets/13523904/14059058/cf3f0ae2-f36f-11e5-8515-c80018010f28.png)

Normal:
![image](https://cloud.githubusercontent.com/assets/13523904/14059062/049d3ac4-f370-11e5-915b-bb040616be6b.png)

**Comment by david50407** [comment]
Please read README first, try `QT_HARFBUZZ=old ./chewing-editor`
