### ISSUE TITLE
Confirm window when removing a phrase.

### ISSUE THREAD

**Issue by iceman126** [chewing/chewing-editor#155]
The color of the "remove" button and "add" is the same. It is easy to press the wrong button. Maybe add a confirm windows when user press "delete" button to prevent user delete phrases accidentally.

**Comment by YWJamesLin** [comment]
Added in [https://github.com/chewing/chewing-editor/pull/158](PR #158 )

**Comment by david50407** [comment]
We are planning to make these into icon buttons (#45), and the discussion [here](https://groups.google.com/forum/#!topic/chewing-devel/Uml1-gyqKqw) is for the UNDO function to prevent user get a wrong action.

**Comment by kidwm** [comment]
Close this after UNDO function finished.
