### ISSUE TITLE
Show notification after user failed to add a phrase

### ISSUE THREAD

**Issue by skellroyal** [chewing/chewing-editor#160]
In now operating behavior, user have to click the refresh button after finish add a phase, and then scroll the phase list to the bottom to check whether the phase has been add or not. To user, it is very unfriendly. If we can do it in one step, why should we take two? 
Moreover, when user finish add a phase, there are no any notify message, it might let someone feel confuse e.g. “Is it fail? Or success?”

**Comment by david50407** [comment]
> In now operating behavior, user have to click the refresh button after finish add a phase, 

No, if addition is succeed, the phrase will be add into list immediately and show the notification to tell user it's added. As screenshot below.

![image](https://cloud.githubusercontent.com/assets/841969/14060868/290f2b42-f3ac-11e5-8beb-c29abaa06a6b.png)

**Comment by skellroyal** [comment]
Here is my add process.

1. Click 'Add' button and type a phrase
![1s](https://cloud.githubusercontent.com/assets/1085622/14060970/17aeef4c-f3af-11e5-8bca-25c87b46d0d7.png)

2. After add phrase (didn't show any notify message)
![2s](https://cloud.githubusercontent.com/assets/1085622/14060975/2dd802cc-f3af-11e5-9d2a-cb0419e2c892.png)

3. Click 'Refresh' button (# of phrases change to 61)
![3s](https://cloud.githubusercontent.com/assets/1085622/14060985/755be082-f3af-11e5-8b9b-14d25a95e105.png)

4. Scroll down to see the result (not friendly to user)
![4s](https://cloud.githubusercontent.com/assets/1085622/14060990/93655e78-f3af-11e5-9383-f167a382a11d.png)

**Comment by david50407** [comment]
ref: https://github.com/chewing/chewing-editor/issues/99

So you failed to add the phrase because you didn't provide the bopomofo for the phrase.
And when you clicked `Refresh`, it loaded the phrase auto-added by chewing itself.

You're right, maybe we have to show some message to tell user the operation is failed.
