### ISSUE TITLE
Show application icon on non-Windows

### ISSUE THREAD

**Issue by david50407** [chewing/chewing-editor#163]
As title, for now, we only show `rc/chewing-editor.ico` as application icon on Windows.

**Comment by Chocobo1** [comment]
cinnamon DE doesn't show icon for all apps so I'm not sure how it works on other DEs (and osx).

**Comment by jserv** [comment]
Is this issue valid for latest chewing-editor since PNG icon is used instead?

**Comment by david50407** [comment]
![image](https://cloud.githubusercontent.com/assets/841969/14237569/62721b08-fa58-11e5-84ca-0398288d745d.png)

Yes, it's still showing the default icon on Ubuntu.

**Comment by Chocobo1** [comment]
@david50407 
Please test PR #174.

**Comment by david50407** [comment]
@Chocobo1 works on Ubuntu

**Comment by Chocobo1** [comment]
>@Chocobo1 works on Ubuntu

Thanks for confirming.
