### ISSUE TITLE
Phrase not added if using BoPoMoFo as input

### ISSUE THREAD

**Issue by eugenelet** [chewing/chewing-editor#165]
![image](https://cloud.githubusercontent.com/assets/13523904/14061181/d6d23514-f3b4-11e5-8ec4-35f669ad8286.png)
Just as simple warning.

**Comment by david50407** [comment]
what did you typed as the phrase and bopomofo?

**Comment by eugenelet** [comment]
I don't really know how to type bopomofo, I just typed a random chinese word for the phrase and a random "bopomofo" for bopomofo

**Comment by eugenelet** [comment]
My environment:
![image](https://cloud.githubusercontent.com/assets/13523904/14061994/91110d0a-f3ca-11e5-9e7a-f73a6feab33b.png)

**Comment by david50407** [comment]
If you didn't add the phrase with the same length of words in bopomofo, it would cause the operation failed and got the warning message in console.

**Comment by eugenelet** [comment]
Oh I see... Thanks! :)

**Comment by kidwm** [comment]
Ref: #160
