### ISSUE TITLE
Add Mac OS X CI on Travis

### ISSUE THREAD

**Issue by david50407** [chewing/chewing-editor#172]
Travis support OS X CI now (https://docs.travis-ci.com/user/osx-ci-environment/).
Maybe we can get auto-testing for OS X on Travis?

**Comment by Chocobo1** [comment]
Not working yet: https://github.com/Chocobo1/chewing-editor/commit/34e074c19397d79b61f462b7743c32d93cc1f69d. Due to apple-clang not working well with C++11, probably need to use gcc.
Also not sure how long will it take to get gcc installed.

**Comment by david50407** [comment]
We can install gcc on Travis with homebrew package support. I'll try it

**Comment by Chocobo1** [comment]
>And we can keep Travis cache for the environment

Last time I checked (1, 2 weeks ago), Travis still didn't enable cache in osx env.

> We can install gcc on Travis with homebrew package support. I'll try it

If you can open a PR (with my commit followed by your "fixing" commits), that would be great.
