### ISSUE TITLE
[Bug] Import feature doesn't work.

### ISSUE THREAD

**Issue by PeterDaveHello** [chewing/chewing-editor#187]
Tested on a clean **Ubuntu 16.04 LTS** amd64 and **Linuxmint Cinnamon 17.3** amd64 which is based on Ubuntu 14.04 LTS.

The export feature works well, but the import feature doesn't work here, it will open a window to let me choose the file to be imported, but after that, nothing happened, that's old, I'm not sure if it's a bug or it's my problem, I try to use a clean Ubuntu to reproduce this problem and it just happened.

**Comment by czchen** [comment]
You can use `chewing-editor -d` to enable debug mode to see if there is any error message.

**Comment by PeterDaveHello** [comment]
@czchen Thanks, I will.

**Comment by PeterDaveHello** [comment]
Here are some logs, I'm still tracing.

First time to click "File / Import" :
```
Debug: import_count =  0  (void ChewingEditor::selectImportFile() ChewingEditor.cpp:112)
Debug: dialogType_ =  11  (void ChewingEditor::execFileDialog(ChewingEditor::DialogType) ChewingEditor.cpp:80)
```

Second time (and after the second time) to click "File / Import" :
```
Debug: import_count =  0  (void ChewingEditor::selectImportFile() ChewingEditor.cpp:112)
Debug: dialogType_ =  0  (void ChewingEditor::execFileDialog(ChewingEditor::DialogType) ChewingEditor.cpp:80)

```

Double click to open a file:
```
Debug: dialogType_ =  0  (void ChewingEditor::finishFileSelection(const QString&) ChewingEditor.cpp:123)
Debug: import_count =  1  (void ChewingEditor::finishFileSelection(const QString&) ChewingEditor.cpp:131)
```

Click a file and then click open button:
```
Debug: dialogType_ =  0  (void ChewingEditor::finishFileSelection(const QString&) ChewingEditor.cpp:123)
Debug: import_count =  1  (void ChewingEditor::finishFileSelection(const QString&) ChewingEditor.cpp:131)

```

**Comment by PeterDaveHello** [comment]
cc @rrobert501128 @hwhung0111

**Comment by PeterDaveHello** [comment]
Just note that even there are 4 phrases in total, the debug message of export still shows 1:
```
Debug: import_count =  1  (void ChewingEditor::finishFileSelection(const QString&) ChewingEditor.cpp:131)
```

**Comment by PeterDaveHello** [comment]
The bug came from #187, revert cc5cd9643583a763592ec5e6993782573c491bae for #49 actually fix this problem.

**Comment by PeterDaveHello** [comment]
@robert501128 @hwhung0111 would you please confirm that?

**Comment by david50407** [comment]
Which version do you use? From apt or build by yourself (from which commit)? Could you provide more information about the environment? And the import json file, please :smile:

**Comment by jserv** [comment]
Cc. @cyng93

**Comment by PeterDaveHello** [comment]
@david50407 build from https://github.com/chewing/chewing-editor/commit/50c105e5ef002eb85fa5e2b0ff144f612ab4ca4b, on Ubuntu 14.04.4 LTS with qt 5.2.1

**Comment by david50407** [comment]
That seems you only trigger the dialog once.

BTW, #187 is trying to solve the problem in #49 that importing will trigger twice event,
And #187 says that `Second trigger should be ignored` but it skipped the first trigger in https://github.com/chewing/chewing-editor/commit/cc5cd9643583a763592ec5e6993782573c491bae#diff-fe73a7ae7fac4644eebd943eeb1959c4R127
I'm going to fix this (by skipping the second trigger correctly), any other thoughts?

**Comment by PeterDaveHello** [comment]
I actually have a patch for this problem, will send it now, just want to confirm the issue first.

**Comment by david50407** [comment]
Yes, I have the same problem on Ubuntu 14.04 /w Qt 5.4.2

**Comment by PeterDaveHello** [comment]
I just sent the patch to #193, would you guys please help review it?

**Comment by hwhung0111** [comment]
I had tried #193, and I think it fix the bug.

**Comment by cyng93** [comment]
> That seems you only trigger the dialog once.

>BTW, #126 is trying to solve the problem in #49 that importing will trigger twice event,
And #126 says that Second trigger should be ignored but it skipped the first trigger in cc5cd96#diff-fe73a7ae7fac4644eebd943eeb1959c4R127
I'm going to fix this (by skipping the second trigger correctly), any other thoughts?

It was my bad in #126 for messing up `import_count++` with `++import_count`, thanks @david50407  for pointing out that.
