### ISSUE TITLE
[Feature]Remove multiple phrases

### ISSUE THREAD

**Issue by Billy4195** [chewing/chewing-editor#202]
It needs to remove multiple phrases sometimes. But now needs to remove them one at a time.

I think it could add checkbox in front of each phrase. The selected phrases will be removed when the remove button is pressed.

**Comment by jserv** [comment]
Please request a specific feature in the manner of this article [How to Request a Feature](https://taskwarrior.org/docs/features.html).

**Comment by Billy4195** [comment]
Hi @jserv ,do you mean add the motivation to add the feature, or describe the detail to implement this feature??

**Comment by Billy4195** [comment]
Oh after traced the code, and tried it. I found it has already have this feature, by pressing CTRL key and using mouse to click several phrase can select them, then clicking the remove button works well.

I think that this feature doesn't  need to be implemented. (I mean add checkbox in front of each phrase on the list of user phrases)
Should I close this issue?

**Comment by jserv** [comment]
Before closing this feature request, you can still improve existing documentation instead. Please send pull request instead.

**Comment by Billy4195** [comment]
But...there is no existing documentation for this project.
If I want to start writing documentation, I should use wiki on GitHub or there exists some better choices.

**Comment by jserv** [comment]
In-program online help would be better than the entries of Wiki pages from users' perspective.

**Comment by david50407** [comment]
@jserv maybe we can try to place a "Help" button in on the interface and link it to github wiki page first?

**Comment by jserv** [comment]
@david50407, Good idea. However, I prefer having in-program help rather than linking to somewhere at first sight.

**Comment by david50407** [comment]
I'm going to close this issue, and the discussion on documents can be continued in #205.
