### ISSUE TITLE
"About QT" window is over screen size 

### ISSUE THREAD

**Issue by Daichou** [chewing/chewing-editor#208]
Environment
OS: Arch Linux (Linux 4.10.8-1 x86_64)
Display resolution :1920x1080
Desktop environment: gnome3

When I push about in "help" menu and then push "About QT",the window of "About QT" is over the screen size and "OK" Button cannot display in window. Like below:
![](https://i.imgur.com/wCLfNN3.jpg)

**Comment by david50407** [comment]
I'm going to close this issue because this issue should be due to Qt.
