### ISSUE TITLE
The mistakenly chosen character still show up after I choose the correct character

### ISSUE THREAD

**Issue by SeanCCC** [chewing/chewing-editor#222]
Environment : Ubuntu 16.04 on Virtualbox

The mistakenly chosen character still show up after I choose the correct character. To be specific, when I'm using the function add(新增), and type character into the blank bopomofo(注音). I want type  ㄣ. but I made a typo and typed 恩, and then I corrected it and chose ㄣ instead. After I press enter, the whole thing will be like the picture below. The typo I made is still there while they shouldn't. 

![default](https://cloud.githubusercontent.com/assets/11786388/25068304/c1393d62-2291-11e7-8636-a09bfadede2d.PNG)

**Comment by david50407** [comment]
I'm going to close this due to [chewing/libchewing](https://github.com/chewing/libchewing).
