### ISSUE TITLE
Wrong imformation about install requirements in the wiki

### ISSUE THREAD

**Issue by SeanCCC** [chewing/chewing-editor#223]
In wiki->Development->Install Requirements, we are asked to do ```sudo apt-get install libchewing3-dev libqt5webkit5-dev cmake ```. However, if we follow this guide, we'll be faced with the error when we are doing the make.
![default](https://cloud.githubusercontent.com/assets/11786388/25068497/8756ac54-2298-11e7-9616-8082b63762d2.PNG)

solotion: 
Simply add ```sudo apt-get install qttools5-dev-tools``` in the guide.

**Comment by Billy4195** [comment]
I have added the command to solve this problem in wiki page.

**Comment by SeanCCC** [comment]
Cool, I see it on the [installation](https://github.com/chewing/chewing-editor/wiki/Installation) page. I've just edited the [development](https://github.com/chewing/chewing-editor/wiki/Development) too, so no one will meet the same error afterwards.

**Comment by Billy4195** [comment]
Oh, I mistakenly add the solution to wrong page. The installation from package won't meet this problem, I will remove it in the installation page

**Comment by jserv** [comment]
Close at first glance since wiki is updated. Reopen if it still happens.
