### ISSUE TITLE
[Feature Request] Input with less space/enter key

### ISSUE THREAD

**Issue by fapbod** [chewing/chewing-editor#227]
Current Situation
- Only the first candidate character appears after entering.  
If one wants to show the list of candidate characters and select the correct word, one needs to press the space key first. 
- After the selection via the number keys, one needs to press the enter key to complete an input.

Target

- After entering the phonetic notes, the list of candidate words appears without pressing the space key. 
- After the selection via the number keys, the input is done directly without pressing the enter key.

**Comment by david50407** [comment]
I don't think this is relatived to chewing-editor, but several implements.
I'm going to close this issue.
