### ISSUE TITLE
chewing-editior fails to build with new Qt5 >= 5.11

### ISSUE THREAD

**Issue by david-geiger** [chewing/chewing-editor#234]
Hi,

Since new Qt5 5.11 chewing-editor doesn't built anymore, upstream now removed the QT5_USE_MODULES function, so the following patch fixes this issue:

http://svnweb.mageia.org/packages/cauldron/chewing-editor/current/SOURCES/chewing-editor-0.1.1-fix-build-against-qt-5.11.0.patch?view=markup&pathrev=1234419

Regards,
David

**Comment by jserv** [comment]
@david-geiger, Thanks for your contribution. Would you mind if you send pull request(s) instead?
