### ISSUE TITLE
Move to newer GCC?

### ISSUE THREAD

**Issue by david50407** [chewing/chewing-editor#237]
Since Homebrew removed gcc@4.8[^1], Travis CI will fail on every test in macOS environment, that is unhealthy for developments.
And GNU-supported version are 10.2, 9.3, 8.4 now[^2], 4.8 is toooo old, maybe we can move to newer gcc (at least 4.9 for macOS CI)?

[^1]: https://formulae.brew.sh/formula/gcc
[^2]: https://gcc.gnu.org/

**Comment by jserv** [comment]
Great. Did you have proposed pull request(s) associated with newer GCC support?

**Comment by yan12125** [comment]
In https://github.com/chewing/chewing-editor/pull/239, I proposed to switch from Travis CI to GitHub Actions, as travis-ci.org is ceased and travis-ci.com is not free.

> Since June 15th, 2021, the building on travis-ci.org is ceased.

(Mentioned on https://travis-ci.org/github/chewing/chewing-editor)

If that PR is accepted, `.travis.yml` can be dropped, and `gcc@4.8` will no longer be used.

**Comment by jserv** [comment]
> In #239, I proposed to switch from Travis CI to GitHub Actions, as travis-ci.org is ceased and travis-ci.com is not free.
> > Since June 15th, 2021, the building on travis-ci.org is ceased.
> (Mentioned on https://travis-ci.org/github/chewing/chewing-editor)
> If that PR is accepted, `.travis.yml` can be dropped, and `gcc@4.8` will no longer be used.

Agree. Please go ahead for dropping Travis CI.

**Comment by yan12125** [comment]
Thanks, here you go~ https://github.com/chewing/chewing-editor/pull/240
