### ISSUE TITLE
actualize fedora spec file to not contain debug symbols

### ISSUE THREAD

**Issue by danik292** [chewing/chewing-editor#242]
Why?
Because,It will be easier to review for reviewers (me).

Thanks 
Daniel

**Comment by kanru** [comment]
This repository doesn't have spec files. Are you referring to this package review request? https://bugzilla.redhat.com/show_bug.cgi?id=2298050

If so, it would be great if you can point out packaging problems on the bugzilla ticket directly :)

**Comment by danik292** [comment]
Ok I will shout out there.
