### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by czchen** [chewing/chewing-editor#25]
User shall be able to find the following information in about:
* Program name (chewing-editor)
* Version from `git describe`
* Simple describe (from README.md)
* Issue tracker (<https://github.com/chewing/chewing-editor/issues>)
* License

**Comment by david50407** [comment]
I can do this. Should we show the Chewing logo on it?
And for version information, maybe we have to add a field in `config.h.in` for assigning the result of `git describe`?

**Comment by Chocobo1** [comment]
> Should we show the Chewing logo on it?

that would be preferable.

>add a field in config.h.in for assigning the result of git describe?

ok
