### ISSUE TITLE
Visual Studio 2012 Win64 build fail

### ISSUE THREAD

**Issue by ottokang** [chewing/chewing-editor#57]
[CMakeError.txt](https://github.com/chewing/chewing-editor/files/152095/CMakeError.txt)

已經安裝 Cmake、Qt、Visual Studio 2012，不知道還缺少什麼組件

**Comment by Chocobo1** [comment]
Can you try again with git master?
Also, the log from CMakeError.txt isn't useful. You should post the log of your input & cmake/Visual Studio output.

**Comment by Chocobo1** [comment]
Closing as #37 duplicate.
Also you can check out https://github.com/Chocobo1/chewing-editor-build, there is a build script you can follow.
