### ISSUE TITLE
Cannot display Chinese words (including bopomofo)

### ISSUE THREAD

**Issue by david50407** [chewing/chewing-editor#71]
As the snapshot below, it cannot display Chinese words on my Manjaro Linux (which forked from Arch Linux).
The editor is built by myself with Qt 5.1.1 at https://github.com/chewing/chewing-editor/commit/d9b7f5339dc63e8c0554b420fb4d1c5ee369079f.
I also read the issue https://github.com/chewing/chewing-editor/issues/7 and run program with `QT_HARFBUZZ=old` but it acted as the same.

![image](https://cloud.githubusercontent.com/assets/841969/13777354/9d4a435e-eaea-11e5-9d51-950c10ecfe92.png)

**Comment by PingNote** [comment]
Hi David, I'm Manjaro Linux and IBus user , here are some information may be helpful to you .



via https://wiki.archlinux.org/index.php/IBus#Installation : 
> Additionally, to enable IBus for Qt applications, install the [ibus-qt](https://www.archlinux.org/packages/?name=ibus-qt) library.

via https://wiki.archlinux.org/index.php/IBus#IBus :
> Note: You need to have [east Asian fonts](https://wiki.archlinux.org/index.php/Fonts_FAQ#Chinese.2C_Japanese.2C_Korean.2C_Vietnamese) installed if you want to enter Chinese, Japanese, Korean or Vietnamese characters.

via https://wiki.archlinux.org/index.php/IBus#Chinese_input :
> If you encounter problems when using Chinese input, check your locale setting. For example in Taiwan, export LANG=zh_TW.UTF-8.

**Comment by david50407** [comment]
@PingNote hi, I can type chinese in chewing-editor and terminal but only terminal shows the correct words

**Comment by Chocobo1** [comment]
>hi, I can type chinese in chewing-editor and terminal but only terminal shows the correct words

I guess your UI font doesn't support Chinese chars? can you try another font?

**Comment by david50407** [comment]
@Chocobo1 It fixed after I changed UI font, thx :)

**Comment by cyng93** [comment]
@david50407 I am also having the issue of can't display Bopomofo properly in the chewing-editor.
I try to fix the problem by following the way mentioned in issue #7 , but I doesn't understand what exactly does "run the program with QT_HARFBUZZ=old " means. 

I had try to run the program like 
`$ ./chewing-editor -Qt_HARFBUZZ=old`
`$ cmake . -DQt_HARFBUZZ=old`
but both of the ways mentioned above doesn't seems to be the right way.
Any helps will be appreciated.

**Comment by david50407** [comment]
@cyng93 try 

```
QT_HARFBUZZ=old ./chewing-editor
```

**Comment by cyng93** [comment]
Yep that fixed my problem, thanks a lot !
