### ISSUE TITLE
Choosing characters by using number keyboard

### ISSUE THREAD

**Issue by alwayschoco** [chewing/chewing-editor#72]
When I want to choose the characters on the selection pages after selection page1 ,  if I type the number which I wanted by using number keyboard, the character will be the one on selection page1

But it won't happen if I choose it by using horizontal numbers.

For example: 
If I type 媒(ㄇㄟˊ) at first, and I want to choose 霉(at another selection page)，

- the first selection page looks like this
![bug1](https://cloud.githubusercontent.com/assets/17408932/13779941/58fa91b4-eaf8-11e5-97bf-ddcdc8543cc8.PNG)

- switch to another selection page like this
![bug2](https://cloud.githubusercontent.com/assets/17408932/13779955/62fb4faa-eaf8-11e5-9e73-8d6f2139a2ac.PNG)

- If I choose 霉 by using number keyboard on the right side of keyboard, the result will be 眉 which is on the first page
![bug3](https://cloud.githubusercontent.com/assets/17408932/13779961/69a2d706-eaf8-11e5-9da2-0ba04bb6845a.PNG)

- But if I try it by using the horizontal number keys, the result will be correct
![bug4](https://cloud.githubusercontent.com/assets/17408932/13779967/6dd6a99c-eaf8-11e5-90b5-c94e1118d41c.PNG)

**Comment by david50407** [comment]
This is not about `chewing-editor`.
Could you please report to [chewing/libchewing](https://github.com/chewing/libchewing/issues) ?
