### ISSUE TITLE
Archlinux software repository not include chewing-editor

### ISSUE THREAD

**Issue by PingNote** [chewing/chewing-editor#73]
![image](https://cloud.githubusercontent.com/assets/3262833/13784407/11f7a8d0-eb0a-11e5-9808-e64452aafcb8.png)

I want only type `sudo pacman -S chewing-editor` or `yaourt chewing-editor` to auto install chewing-editor , I need Workshop > < "

**Comment by Chocobo1** [comment]
* packagers, maybe also ask on the distros forum... but I'm interested in becoming a packager for this, let me try.
* I guess there should be 2 aur: `chewing-editor` (for tagged releases), `chewing-editor-git` (for git master branch)
* are you familiar with it's dependency? I only know dependencies for make process, what about it's run dependency?

**Comment by PingNote** [comment]
Hi @Chocobo1 , some dependency information via https://fossapc.hackpad.com/Homework-3--FdMpqvJbKYL :
- libchewing
- qt5-webkit
- qt5-tools (addition)
- ibus-qt (addition)

I don't know Official repositories behavior,
but if will in AUR , we can write build-script , auto `cmake` and `make` chewing-editor .

Will we need Arch Build System (ABS) ?

**Comment by Chocobo1** [comment]
Thank you!

>Will we need Arch Build System (ABS) ?

Yes, it's required on your local machine for using AUR.

>some dependency information via https://fossapc.hackpad.com/Homework-3--FdMpqvJbKYL :

I didn't know there was some homework (activity) going on, I better not cross over the line XD

**Comment by PingNote** [comment]
Thank you @Chocobo1 ! it's work , and I voted it XD
![image](https://cloud.githubusercontent.com/assets/3262833/13807685/602c6138-eb9d-11e5-86bb-8e904c1ddfdb.png)

How any tutorial can make me have the ability to help maintain this AUR > < "

**Comment by Chocobo1** [comment]
>How any tutorial can make me have the ability to help maintain this AUR > < "

not aware of any tutorial... I just follow what arch wiki says (topic AUR)

**Comment by david50407** [comment]
@Chocobo1 maybe @PingNote means how to contribute to this AUR?

**Comment by Chocobo1** [comment]
>@Chocobo1 maybe @PingNote means how to contribute to this AUR?

Maybe leave a comment for me (at the AUR link)? Comment section will be available after login into AUR.
