### ISSUE TITLE
Can not remove all exist phrases on the white board in one time 

### ISSUE THREAD

**Issue by yojo3000** [chewing/chewing-editor#81]
1. It should have a button on top menu or right click menu if someone want to clean the white board.

2. Additionally, the selected bar on the phrases white board should not disappear after someone remove a phrase

select one phrase
![screen shot 2016-03-16 at 7 47 19 pm](https://cloud.githubusercontent.com/assets/8850565/13811447/bbe5619c-ebb0-11e5-9e6d-6b5e7c4b48b7.png)

remove the phrase
![screen shot 2016-03-16 at 7 54 17 pm](https://cloud.githubusercontent.com/assets/8850565/13811478/f22dde6e-ebb0-11e5-8c2e-a10cc217194a.png)

if someone want to keep deleteing phrases on white board, it will be a tough job

**Comment by yojo3000** [comment]
I think "keep on clicking the remove button" is the first idea of user who want to remove multiple phrases
#65 just provide another way for user to remove phrases but not in the first mind I thought~

**Comment by kidwm** [comment]
@yojo3000 that way will make user accidentally delete other phrases.

**Comment by Chocobo1** [comment]
@yojo3000 
#65 is closed, if you agree with the current solution can you close this issue?

**Comment by redfish-lee** [comment]
These shortcuts works and is instinctive to me: 
- `Shift` + range to **select** and remove multiple items 
- `Ctrl`+`A` to **select all** whiteboard items and remove
