### ISSUE TITLE
the "about chewing-editor" item in help menu does not work

### ISSUE THREAD

**Issue by ShengYenPeng** [chewing/chewing-editor#85]
If I select "about QT", I will get
![about qt](https://cloud.githubusercontent.com/assets/16522555/13819539/ce073d36-ebd4-11e5-8027-0fe9147d493a.PNG)

but if I select "about chewing-editor", it is no response
![no_response](https://cloud.githubusercontent.com/assets/16522555/13819481/939ef56c-ebd4-11e5-95f5-d23c27438874.png)

**Comment by david50407** [comment]
yes, this is not implemented yet.
ref: https://github.com/chewing/chewing-editor/issues/25

**Comment by ShengYenPeng** [comment]
OK!

Should I delete this issue?

**Comment by jserv** [comment]
No, since it exists, you should keep the issue open.

**Comment by david50407** [comment]
This is done on https://github.com/chewing/chewing-editor/pull/120#event-604902081
