### ISSUE TITLE
CapsLock disables chinese typing

### ISSUE THREAD

**Issue by gocreating** [chewing/chewing-editor#92]
## Expected behavior

CapsLock should not toggle typing mode under chinese typing mode.

## Actual behavior

I can only type capital letters with `CapsLock` enabled.

## Information to reproduce

OS: Ubuntu 15.10 64bit
Keyboard input method system: iBus

**Comment by david50407** [comment]
It's Chewing's behavior that trigger english mode when capital locking.

**Comment by kidwm** [comment]
or you can file an issue to libchewing.

**Comment by kidwm** [comment]
BTW, FYI: https://groups.google.com/forum/#!topic/chewing-devel/fkBzRYwJP5M
