### ISSUE TITLE
Character selection table didn't pop out sometimes

### ISSUE THREAD

**Issue by WakeupTsai** [chewing/chewing-editor#93]
Sometimes I press the down button or space button the character selection table didn't show up

for example, I type "你"
![a](https://cloud.githubusercontent.com/assets/9034508/13855297/9e4bb924-ecaa-11e5-8d85-de7ca2430766.png)

and I want to change it to "妳", so I press the space button, but it just move the cursor to left and nothing happen
![b](https://cloud.githubusercontent.com/assets/9034508/13855424/60d3151e-ecab-11e5-85b4-cf61ace7bc92.png)

but it should like this
![c](https://cloud.githubusercontent.com/assets/9034508/13855432/6ae215c8-ecab-11e5-8761-c93374b4fc6a.png)

**Comment by ShengYenPeng** [comment]
I also have same problem in Ubuntu15.10,

But it works correctly in Windows7

**Comment by kidwm** [comment]
It is working under ibus-chewing.
and this is out of scope of chewing-editor.
