### ISSUE TITLE
Selecting character makes page disappear in Windows7 Chrome

### ISSUE THREAD

**Issue by ShengYenPeng** [chewing/chewing-editor#96]
Hi,

when I download and rename my file in "save as" page,

selecting character makes "save as" page disappear, like:
![sleceting character_3](https://cloud.githubusercontent.com/assets/16522555/13867097/a8b30682-ecf6-11e5-9feb-c0da4fc3b1aa.PNG)

it seems that selecting character makes browser page pop out, like
![sleceting character_6](https://cloud.githubusercontent.com/assets/16522555/13867206/cc6f7528-ecf7-11e5-9596-0adf9d8da7a7.PNG)

and I find microsoft-chewing also have some problem,but it will make "save as" page appear in front again(you may feel a little flash, that is what it does)

**Comment by kidwm** [comment]
you should file issue to https://github.com/EasyIME/PIME/issues
