### ISSUE TITLE
Can't using the number keyboard

### ISSUE THREAD

**Issue by martian206** [chewing/chewing-editor#97]
I am using the Ubuntu 15.10 and the ibus-chewing. After I setup Chewing, I can't type numbers from the right-side number keyboard, even if I change the input to the cangjie3, and I am sure that I didn't lock my number keyboard when I tried to type numbers.

**Comment by david50407** [comment]
This is out of chewing-editor, maybe you can report it to https://github.com/definite/ibus-chewing/issues .
And is https://github.com/definite/ibus-chewing/issues/57 the same issue you mentioned?
