### ISSUE TITLE
new userphrase should be added into list after click "OK"

### ISSUE THREAD

**Issue by ShengYenPeng** [chewing/chewing-editor#99]
Hi,

I add new userphrase via "Add new phrase",
![image](https://cloud.githubusercontent.com/assets/16522555/13870321/4cf9a112-ed18-11e5-8379-3040b3b57f3a.png)

and I think the new phrase should appear in the list after I click "OK", 
but I should click refresh button to make new phrase appear now.

The delete button works well, it just delete phrase after I delete, 
I don't need to click refresh button to make phrase disappear.

**Comment by ShengYenPeng** [comment]
the reason is that I just enter phrase and leave empty in bopomofo, so the phrase is pushed into ctx.   
after I click refresh then the phrase is added into list.

but I think it could add phrase without bopomofo after clicking OK

**Comment by david50407** [comment]
Now can only add phrase by giving both phrase and bopomofo. See https://github.com/chewing/chewing-editor/issues/2

**Comment by david50407** [comment]
Chewing can automatically remember phrases when you are typing.
You thought that you added the phrase without bopomofo successfully because you could see it after refreshing the list. But maybe it just failed and you loaded the same phrase remembered by itself (not added from chewing-editor).

**Comment by kidwm** [comment]
@ShengYenPeng see https://github.com/chewing/chewing-editor/issues/94

**Comment by ShengYenPeng** [comment]
ok, thanks!

I think now that we can add phrase just by typing,
we should let chewing-editor have same behavior, because typing bopomofo is very time-consuming.
If editor found that user don't type bopomofo, maybe it can call API in libchewing to return bopomofo.

or the simplest idea is that if editor found that no bopomofo, just call refresh, so that the word would be added into list by libchewing.

**Comment by david50407** [comment]
> If editor found that user don't type bopomofo, maybe it can call API in libchewing to return bopomofo.

See https://github.com/chewing/libchewing/issues/143

> or the simplest idea is that if editor found that no bopomofo, just call refresh, so that the phrase would be added into list by libchewing.

But it's not always become into one phrase.
Maybe "蜘蛛人" you typed will become "蜘蛛" and "人",  it's not the phrase wanted by user.

**Comment by ShengYenPeng** [comment]
ok, I got it.

thanks!

**Comment by ShengYenPeng** [comment]
Hi @david50407 ,

According chewing can automatically remember phrases when you are typing and 
refresh will push back these phrase into chewing-list, 
I think I can use the phrase in the bottom of chewing-list to create the phrase that I want add.

I wrote some code into add function in UserphraseModel.cpp, and it seems work.

```
    if (ret > 0) {
        emit beginResetModel();
        userphrase_.insert(Userphrase{
            phrase,
            bopomofo
        });
        emit endResetModel();
        emit addNewPhraseCompleted(userphrase_[userphrase_.size()-1]);
    } else {
        qWarning() << "chewing_userphrase_add() returns" << ret;
		
		//----------  NEW  ( add userphrase without bopomofo) ------------------
		
		// refresh to make related phrase inserted into bottom of chewing-editor list
		refresh();
        
        int newPhrasePos = phrase.size()-1;
        QString tmpBopomofo;
        int idx = userphrase_.size()-1;
        
        bool foundMatchPhrase = false;
        
		//iterative searching correct phrase in userphrase list and add record bopomofo
        while(newPhrasePos >=0 ){
            
            foundMatchPhrase = false;            
            idx = userphrase_.size()-1;
            
			//searching correct phrase
            while( foundMatchPhrase == false  ){
                
               QString comparePhrase = userphrase_[idx].phrase_;
                
                if( comparePhrase.size() > newPhrasePos+ 1)
                {
                    --idx;
                    continue;
                }          
                
                
                for( int phraseShift= 0 ; phraseShift < comparePhrase.size() ; ++phraseShift  ){
                    if(  phrase[newPhrasePos - phraseShift ] != comparePhrase[ comparePhrase.size() -1-phraseShift ] ){
                        --idx;
                        break;
                    }
                    else if( phrase[newPhrasePos - phraseShift ] == comparePhrase[ comparePhrase.size() -1-phraseShift ] && phraseShift ==  comparePhrase.size()-1 )
                        foundMatchPhrase = true;
                }
                
             }
            
			// recording bopomofo
            if( newPhrasePos ==  phrase.size() -1)
                tmpBopomofo=userphrase_[idx].bopomofo_;
            else
                tmpBopomofo = userphrase_[idx].bopomofo_+" "+tmpBopomofo;
            
            newPhrasePos -= userphrase_[idx].phrase_.size();
        }
        
		//add
        if( newPhrasePos == - 1 & phrase.size() != 0)
        {
            add( phrase ,  tmpBopomofo );
        }
        
		//--------------------------------------------
    }
```

example: 

![1](https://cloud.githubusercontent.com/assets/16522555/13976782/252073fc-f0fe-11e5-80c7-3d99006f5437.PNG)
![2](https://cloud.githubusercontent.com/assets/16522555/13976783/2521ab96-f0fe-11e5-91b9-3c749b9d1dbd.PNG)
![3](https://cloud.githubusercontent.com/assets/16522555/13976785/2522f6d6-f0fe-11e5-8b31-65c3ef4a609e.PNG)
![4](https://cloud.githubusercontent.com/assets/16522555/13976786/25244e8c-f0fe-11e5-95c6-e1b10e755685.PNG)
![5](https://cloud.githubusercontent.com/assets/16522555/13976784/2522d5c0-f0fe-11e5-99a0-c9ebdc345393.PNG)
![6](https://cloud.githubusercontent.com/assets/16522555/13976787/252574b0-f0fe-11e5-89d0-c1afed8c3a1b.PNG)
![7](https://cloud.githubusercontent.com/assets/16522555/13976788/254683bc-f0fe-11e5-83fb-d61743821585.PNG)
![8](https://cloud.githubusercontent.com/assets/16522555/13976789/254a4f38-f0fe-11e5-8454-6c1a07099675.PNG)
![9](https://cloud.githubusercontent.com/assets/16522555/13976790/254bbd32-f0fe-11e5-8975-d8ea45282b22.PNG)
![10](https://cloud.githubusercontent.com/assets/16522555/13976792/254ce572-f0fe-11e5-98eb-5f83a318a7d1.PNG)
![11](https://cloud.githubusercontent.com/assets/16522555/13976791/254bc8c2-f0fe-11e5-8122-2bfee1dcd643.PNG)

**Comment by ShengYenPeng** [comment]
I found that the code can't handle the invalid phrase like: "哈囉a",
and the chewing-editor would crash...

**Comment by jserv** [comment]
Please always clip your screenshots. We would crop pictures to concentrate on major difference.

**Comment by ShengYenPeng** [comment]
OK! 
I modified the screenshots.
